# Setup
title:        "Блог лайтовый: 1 шт."
tagline:      "о наболевшем и не только"
baseurl:      ""
destination:  "_site"
url:          "https://eligantru.github.io"
paginate:     1
locale:       "en"

# About/contact
author:
  name:       Nick Yegorov
  url:        https://github.com/eligantRU

# Plugins
plugins:
  - jekyll-paginate

#Others
markdown: kramdown
